name: xarray_extras-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - ipython=6.2.1
  - dask
  - flake8
  - matplotlib
  - numba
  - numpy=1.13
  - numpydoc=0.7.0
  - pandas=0.21.0
  - scipy=1.0
  - sphinx=1.5
  - sphinx_rtd_theme
  - xarray
