name: xarray-docs
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - ipython=6.2.1
  - dask=0.16.0
  - flake8
  - numpy=1.13
  - numpydoc=0.7.0
  - pandas=0.21.0
  - scipy=1.0
  - sphinx=1.5
  - xarray
